//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountApp
    {
        public int AppID { get; set; }
        public int AccountID { get; set; }
        public bool Activated { get; set; }
        public bool Installed { get; set; }
        public bool IsTrial { get; set; }
        public Nullable<System.DateTime> TrialStart { get; set; }
        public Nullable<System.DateTime> TrialExpire { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> AppExpires { get; set; }
        public bool AutoUserLicenseAllocation { get; set; }
        public int UserPoolCount { get; set; }
        public bool IsConverted { get; set; }
        public string APIKey { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual App App { get; set; }
    }
}
