//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addressbook
    {
        public int AddressbookID { get; set; }
        public int AccountID { get; set; }
        public int AppID { get; set; }
        public int SOAssociateID { get; set; }
        public int SOCompanyID { get; set; }
        public int SOPersonID { get; set; }
        public string PublishName { get; set; }
        public string PublishURL { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual App App { get; set; }
    }
}
