//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIKey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APIKey()
        {
            this.MachineName = new HashSet<MachineName>();
        }
    
        public int APIKeyId { get; set; }
        public int AppId { get; set; }
        public int AccountId { get; set; }
        public string APIKeyValue { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual App App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineName> MachineName { get; set; }
    }
}
