//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App()
        {
            this.AccountApp = new HashSet<AccountApp>();
            this.AccountAppAssociate = new HashSet<AccountAppAssociate>();
            this.Addressbook = new HashSet<Addressbook>();
            this.APIKey = new HashSet<APIKey>();
            this.RelationWise = new HashSet<RelationWise>();
            this.AppIcons = new HashSet<AppIcons>();
            this.AppPrivateKey = new HashSet<AppPrivateKey>();
            this.AppSystemUserToken = new HashSet<AppSystemUserToken>();
            this.BisnodeManager = new HashSet<BisnodeManager>();
            this.Converter = new HashSet<Converter>();
            this.DataSync = new HashSet<DataSync>();
            this.ElasticIO = new HashSet<ElasticIO>();
            this.InstallInfo = new HashSet<InstallInfo>();
            this.MirroringLog = new HashSet<MirroringLog>();
            this.PBXDial = new HashSet<PBXDial>();
            this.PDFManager = new HashSet<PDFManager>();
            this.Session = new HashSet<Session>();
            this.Signicat = new HashSet<Signicat>();
            this.Zapier = new HashSet<Zapier>();
        }
    
        public int AppID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Controller { get; set; }
        public bool Enabled { get; set; }
        public string AppVersion { get; set; }
        public string AppAboutText { get; set; }
        public string AppAboutTextShort { get; set; }
        public Nullable<int> TrialDays { get; set; }
        public bool SendExpireMails { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string SOStartURL { get; set; }
        public string SOAdminURL { get; set; }
        public int OnPremiseState { get; set; }
        public int SOOnlineState { get; set; }
        public string SOAppID { get; set; }
        public string ApplicationToken { get; set; }
        public int GlobalSettingsId { get; set; }
        public bool Maintenance { get; set; }
        public string MaintenanceText { get; set; }
        public bool MaintenancePlanned { get; set; }
        public string MaintenancePlannedText { get; set; }
        public int UserPoolCount { get; set; }
        public string AlternateRedirectURL { get; set; }
        public bool HasMirroring { get; set; }
        public bool HasMachineNameValidation { get; set; }
        public bool DebugEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountApp> AccountApp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountAppAssociate> AccountAppAssociate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Addressbook> Addressbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APIKey> APIKey { get; set; }
        public virtual Globals Globals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationWise> RelationWise { get; set; }
        public virtual AppState AppState { get; set; }
        public virtual AppState AppState1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppIcons> AppIcons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppPrivateKey> AppPrivateKey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSystemUserToken> AppSystemUserToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BisnodeManager> BisnodeManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Converter> Converter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataSync> DataSync { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElasticIO> ElasticIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallInfo> InstallInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MirroringLog> MirroringLog { get; set; }
        public virtual MirroringStatus MirroringStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBXDial> PBXDial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PDFManager> PDFManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signicat> Signicat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapier> Zapier { get; set; }
    }
}
