//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppIcons
    {
        public int AppIconID { get; set; }
        public int AppID { get; set; }
        public Nullable<int> ImageSizeAppLogo { get; set; }
        public string ImageNameAppLogo { get; set; }
        public byte[] ImageDataAppLogo { get; set; }
        public Nullable<int> ImageSizeTrialLogo { get; set; }
        public string ImageNameTrialLogo { get; set; }
        public byte[] ImageDataTrialLogo { get; set; }
    
        public virtual App App { get; set; }
    }
}
