//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppOnlineProvisioning
    {
        public int AppOnlineProvisioningId { get; set; }
        public string ProvisioningKey { get; set; }
        public string ProvisioningValue { get; set; }
    }
}
