//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSystemUserToken
    {
        public int AppID { get; set; }
        public int ConnectionID { get; set; }
        public string SystemUserToken { get; set; }
    
        public virtual App App { get; set; }
        public virtual Connection Connection { get; set; }
    }
}
