//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BisNodeInfo
    {
        public int BisNodeInfoID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public byte[] LastUpdated { get; set; }
        public string SystemId { get; set; }
        public string GlobalPARIDWorksite { get; set; }
        public Nullable<int> DatabaseWorkSiteID { get; set; }
        public string WorkSiteStatusCode { get; set; }
        public string WorkSiteStatusDescription { get; set; }
        public string WorksiteName { get; set; }
        public string Department { get; set; }
        public string PostalAddressCo { get; set; }
        public string PostalAddressLine1 { get; set; }
        public string PostalAddressLine2 { get; set; }
        public string PostalAddressZipcode { get; set; }
        public string PostalAddressCity { get; set; }
        public string PostalAddressCountry { get; set; }
        public string VisitingAddressCo { get; set; }
        public string VisitingAddressLine1 { get; set; }
        public string VisitingAddressLine2 { get; set; }
        public string VisitingAddressZipcode { get; set; }
        public string VisitingAddressCity { get; set; }
        public string WorkSiteFaxNo { get; set; }
        public string WorkSiteTelephoneNo { get; set; }
        public string VisitingAddressCountry { get; set; }
        public string WorkSiteMobileNo { get; set; }
        public string WorkSiteMainBusinessCode { get; set; }
        public string WorkSiteMainBusinessDesc { get; set; }
        public string ShareCapitalEUR { get; set; }
        public string ShareCapitalCode { get; set; }
        public string ShareCapitalDescription { get; set; }
        public string ShareCapitalStartingDate { get; set; }
        public string ShareCapitalEndingDate { get; set; }
        public string CompanyTurnoverEUR { get; set; }
        public string CompanyTurnoverStartingDate { get; set; }
        public string CompanyTurnoverEndingDate { get; set; }
        public string CompanyTurnoverCode { get; set; }
        public string CompanyTurnoverDescription { get; set; }
        public string MunicipalityCode { get; set; }
        public string MunicipalityName { get; set; }
        public string CountyCode { get; set; }
        public string CountyName { get; set; }
        public string WorkForceRegionCode { get; set; }
        public string WorkForceRegionName { get; set; }
        public string AlternativeBlockRegionCode { get; set; }
        public string AlternativeBlockRegionName { get; set; }
        public string GeographyZipCode { get; set; }
        public string GeographyCity { get; set; }
        public string GeographyCountryCode { get; set; }
        public string GeographyCountryDescription { get; set; }
        public string TypeOfWorkSiteCode { get; set; }
        public string TypeOfWorkSiteDescription { get; set; }
        public string VATno { get; set; }
        public string LegalName { get; set; }
        public string LegalFormCode { get; set; }
        public string LegalFormDescription { get; set; }
        public string TypeOfCompanyCode { get; set; }
        public string TypeOfCompanyDescription { get; set; }
        public string OrganizationOfficialWorksiteN { get; set; }
        public string OrganizationCompanyNumber { get; set; }
        public string NoOfEmployeesAtWSCode { get; set; }
        public string NoOfEmployeesAtWSDesc { get; set; }
        public string NoOfOfficeEmployeesAtWSCode { get; set; }
        public string NoOfOfficeEmployeesAtWSDesc { get; set; }
        public string NoOfWorkSites { get; set; }
        public string TotalNoOfEmployeesCode { get; set; }
        public string TotalNoOfEmployeesDesc { get; set; }
        public string NoOfOfficeEmployeesAtComCode { get; set; }
        public string NoOfOfficeEmployeesAtComDesc { get; set; }
        public string GroupParentCompanyNumber { get; set; }
        public string GroupParentCompanyName { get; set; }
        public string GroupParentCountry { get; set; }
        public string EmailWorksite { get; set; }
        public string wwwaddressWorksiteCompany { get; set; }
        public string TurnoverChangeCode { get; set; }
        public string TurnoverChangeDesc { get; set; }
        public string TurnoverChangeValue { get; set; }
        public string TurnoverChangeStart { get; set; }
        public string TurnoverChangeEnd { get; set; }
        public string RatingCode { get; set; }
        public string RatingDesc { get; set; }
        public string RatingCompanyNo { get; set; }
        public string RatingSource { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public string TypeOfRecord { get; set; }
        public string InfoLevel { get; set; }
        public string FirstName { get; set; }
        public string FamilyName { get; set; }
        public string BusinessPositionCode { get; set; }
        public string BusinessPositionDescription { get; set; }
        public string DepartmentContact { get; set; }
        public string WorkSiteNameLine1 { get; set; }
        public string WorkSiteNameLine2 { get; set; }
        public string PostalAddress { get; set; }
        public Nullable<int> DatabasePersonId { get; set; }
        public Nullable<int> DatabaseLinkId { get; set; }
        public string PersonStatusCode { get; set; }
        public string PersonStatusDescription { get; set; }
        public string LinkStatusCode { get; set; }
        public string LinkStatusDescription { get; set; }
        public string GlobalPARIDPerson { get; set; }
        public string GlobalPARIDLink { get; set; }
        public string VisitingAddress { get; set; }
        public string LineOfBusinessCode { get; set; }
        public string LineOfBusinessDescription { get; set; }
        public string EmailPerson { get; set; }
        public string OfficialCompanyRegNo { get; set; }
        public string ChangeDateDelete { get; set; }
        public string ChangeDateNew { get; set; }
        public string ChangeDateWorkSiteName { get; set; }
        public string ChangeDatePostalAddress { get; set; }
        public string ChangeDateWorkSiteStatus { get; set; }
        public string ChangeDatePostalZipcode { get; set; }
        public string ChangeDateDepartment { get; set; }
        public string ChangeDatePersonDelete { get; set; }
        public string ChangeDatePersonNew { get; set; }
        public string ChangeDatePersonFirstLastName { get; set; }
        public string ChangeDatePersonBissPos { get; set; }
        public string ChangeDatePersonLinkStatus { get; set; }
        public string ChangeDatePersonStatus { get; set; }
        public string ChangeDateVisitingAddress { get; set; }
        public string ChangeDateTelephoneNo { get; set; }
        public string ChangeDateNoOfEmplyeesAtWs { get; set; }
        public string ChangeDateZipCodeVisitingAddr { get; set; }
        public string ChangeDateNoOfEmplyeesAtCom { get; set; }
        public string ChangeDateEmailPerson { get; set; }
        public string ChangeDateOfficialComRegNo { get; set; }
        public string ChangeDateTelefaxNo { get; set; }
        public string ChangeDateCompanyTurnover { get; set; }
        public string ChangeDateCounty { get; set; }
        public string ChangeDateMunicipality { get; set; }
        public string ChangeDateWorkForceRegion { get; set; }
        public string ChangeDateLegalName { get; set; }
        public string ChangeDateMainLineOfBusiness { get; set; }
        public string ChangeDateTypeOfWorkSite { get; set; }
        public string ChangeDateNoOfOfficeEmpAtWS { get; set; }
        public string ChangeDateNoOfOfficeEmpAtCom { get; set; }
        public string ChangeDateLegalForm { get; set; }
        public string AddressSource { get; set; }
        public string CustomerRefNo { get; set; }
        public string CustomerContactRefNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
