//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Connection()
        {
            this.Account = new HashSet<Account>();
            this.AppSystemUserToken = new HashSet<AppSystemUserToken>();
            this.MatchPerson = new HashSet<MatchPerson>();
        }
    
        public int ConnectionID { get; set; }
        public string URL { get; set; }
        public string SysUser { get; set; }
        public string SysPassword { get; set; }
        public int WSVersion { get; set; }
        public int WSBuild { get; set; }
        public bool WSHttps { get; set; }
        public string NetServer { get; set; }
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanySerial { get; set; }
        public int PrefDescId { get; set; }
        public bool IsSOOnline { get; set; }
        public string SystemUserToken { get; set; }
        public string ContextIdentifier { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSystemUserToken> AppSystemUserToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchPerson> MatchPerson { get; set; }
    }
}
