//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocArcActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocArcActivity()
        {
            this.DocArcActivity1 = new HashSet<DocArcActivity>();
            this.DocArcAssociation = new HashSet<DocArcAssociation>();
        }
    
        public int ItemId { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public bool IsGroup { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SaleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocArcActivity> DocArcActivity1 { get; set; }
        public virtual DocArcActivity DocArcActivity2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocArcAssociation> DocArcAssociation { get; set; }
    }
}
