//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocArcAssociation
    {
        public int AssociationId { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public int ActivityId { get; set; }
        public string DocumentTypes { get; set; }
        public string AppointmentTypes { get; set; }
    
        public virtual DocArcActivity DocArcActivity { get; set; }
    }
}
