//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public int LogGroupID { get; set; }
        public int TextID { get; set; }
        public string UserID { get; set; }
        public int AccountID { get; set; }
        public int AppID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual LogGroup LogGroup { get; set; }
        public virtual Text Text { get; set; }
    }
}
