//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOISLicenseCompanyKeys
    {
        public int Id { get; set; }
        public int LOISCompanyId { get; set; }
        public string LOISSystemId { get; set; }
        public string LOISSystemLicenseKey { get; set; }
        public Nullable<System.DateTime> LicenseExpires { get; set; }
    
        public virtual LOISLicenseCompany LOISLicenseCompany { get; set; }
    }
}
