//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int MailID { get; set; }
        public int TextID { get; set; }
        public string Subject { get; set; }
    
        public virtual Text Text { get; set; }
    }
}
