//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MirroringStatus
    {
        public int MirroringStatusId { get; set; }
        public bool Locked { get; set; }
        public int LockedByAppID { get; set; }
        public System.DateTime LockedDateTime { get; set; }
    
        public virtual App App { get; set; }
    }
}
