//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionId { get; set; }
        public int AppID { get; set; }
        public bool IsTestSODRedirect { get; set; }
        public bool IsTrialVersion { get; set; }
        public bool IsFromSOAppStore { get; set; }
        public string ConfirmationEmail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
    
        public virtual App App { get; set; }
    }
}
