//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignicatEventStatus
    {
        public int SignicatEventStatus1 { get; set; }
        public string RequestId { get; set; }
        public string TaskId { get; set; }
        public string DocumentId { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int AccountId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string NotificationId { get; set; }
        public string Signee { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
