//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignicatEventLog
    {
        public int SignicatEventLogId { get; set; }
        public int AccountId { get; set; }
        public string RequestId { get; set; }
        public string TaskId { get; set; }
        public int EventTypeId { get; set; }
        public int EventOriginId { get; set; }
        public string Description { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SignicatEventOrigin SignicatEventOrigin { get; set; }
        public virtual SignicatEventType SignicatEventType { get; set; }
    }
}
