//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signicat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Signicat()
        {
            this.SignicatSecureForm = new HashSet<SignicatSecureForm>();
        }
    
        public int SignicatID { get; set; }
        public int AccountID { get; set; }
        public int AppID { get; set; }
        public int SignicatVersion { get; set; }
        public string SignicatService { get; set; }
        public string SignicatUserName { get; set; }
        public string SignicatPassword { get; set; }
        public string SignicatWSUrl { get; set; }
        public int SOAssociateID { get; set; }
        public int SOCompanyID { get; set; }
        public int SOPersonID { get; set; }
        public int SOWebFrontPanelID { get; set; }
        public int SOWebBackPanelID { get; set; }
        public int SOStatusSentUDEFID { get; set; }
        public int SOStatusCompletedUDEFID { get; set; }
        public int SOStatusProcessedUDEFID { get; set; }
        public int SOStatusExpiredUDEFID { get; set; }
        public int SOStatusRejectedUDEFID { get; set; }
        public int SOStatusSignedUDEFID { get; set; }
        public bool Enabled { get; set; }
        public string ThumbPrint { get; set; }
        public bool IsProduction { get; set; }
        public bool IsMultipleDocument { get; set; }
        public bool UseLandingPage { get; set; }
        public string LandingPage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public int SignicatClientReference { get; set; }
        public Nullable<bool> UseSecureForm { get; set; }
        public string DocumentServiceFormID { get; set; }
        public Nullable<bool> UseMultipleSignee { get; set; }
        public Nullable<bool> UseDocumentMerge { get; set; }
        public bool IncludePersonNo { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual App App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignicatSecureForm> SignicatSecureForm { get; set; }
    }
}
