//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignicatEmail
    {
        public int SignicatEmailID { get; set; }
        public int AccountID { get; set; }
        public string EmailSender { get; set; }
        public bool EmailSenderFixed { get; set; }
        public string EmailHeader { get; set; }
        public string EmailNotification { get; set; }
        public string EmailBody { get; set; }
        public string EmailGreetings { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<bool> EmailSignedConfirm { get; set; }
        public Nullable<bool> EmailConfirmFixed { get; set; }
        public string EmailConfirmFixedRecipient { get; set; }
        public string EmailConfirmSender { get; set; }
        public string EmailConfirmHeader { get; set; }
        public string EmailConfirmBody { get; set; }
        public string EmailConfirmGreetings { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
