//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOInclude
    {
        public int SOIncludeID { get; set; }
        public string TableName { get; set; }
        public string KeyField { get; set; }
        public string KeyValue { get; set; }
    }
}
