//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisibleIn
    {
        public int VisibleInID { get; set; }
        public Nullable<int> SOVersion { get; set; }
        public int VisibleInKey { get; set; }
        public string Value { get; set; }
    }
}
