//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DataAccessLayer.PhoneList75 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class SoCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoTimeZone", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class SoTimeZone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoTimeZoneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTimeZoneLocationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTimeZoneId {
            get {
                return this.SoTimeZoneIdField;
            }
            set {
                if ((this.SoTimeZoneIdField.Equals(value) != true)) {
                    this.SoTimeZoneIdField = value;
                    this.RaisePropertyChanged("SoTimeZoneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTimeZoneLocationCode {
            get {
                return this.SoTimeZoneLocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTimeZoneLocationCodeField, value) != true)) {
                    this.SoTimeZoneLocationCodeField = value;
                    this.RaisePropertyChanged("SoTimeZoneLocationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoExceptionInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class SoExceptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendlyTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.SoExceptionInfo InnerExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.SoExceptionInfoParameters ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FriendlyText {
            get {
                return this.FriendlyTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlyTextField, value) != true)) {
                    this.FriendlyTextField = value;
                    this.RaisePropertyChanged("FriendlyText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfoParameters Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExceptionInfoParameters", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", ItemName="SoExceptionInfoParametersKeyValuePair", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class SoExceptionInfoParameters : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExtraInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", ItemName="ExtraInfoNameValuePair", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class SoExtraInfo : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneListItem", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class PhoneListItem : AOS.DataAccessLayer.PhoneList75.Carrier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonDirectPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonCellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonPrivatePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonFaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonPagerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TooltipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonDirectPhone {
            get {
                return this.PersonDirectPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonDirectPhoneField, value) != true)) {
                    this.PersonDirectPhoneField = value;
                    this.RaisePropertyChanged("PersonDirectPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string PersonCellPhone {
            get {
                return this.PersonCellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonCellPhoneField, value) != true)) {
                    this.PersonCellPhoneField = value;
                    this.RaisePropertyChanged("PersonCellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PersonPrivatePhone {
            get {
                return this.PersonPrivatePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonPrivatePhoneField, value) != true)) {
                    this.PersonPrivatePhoneField = value;
                    this.RaisePropertyChanged("PersonPrivatePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PersonFaxNumber {
            get {
                return this.PersonFaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonFaxNumberField, value) != true)) {
                    this.PersonFaxNumberField = value;
                    this.RaisePropertyChanged("PersonFaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PersonPagerNumber {
            get {
                return this.PersonPagerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonPagerNumberField, value) != true)) {
                    this.PersonPagerNumberField = value;
                    this.RaisePropertyChanged("PersonPagerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PersonEmail {
            get {
                return this.PersonEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonEmailField, value) != true)) {
                    this.PersonEmailField = value;
                    this.RaisePropertyChanged("PersonEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Tooltip {
            get {
                return this.TooltipField;
            }
            set {
                if ((object.ReferenceEquals(this.TooltipField, value) != true)) {
                    this.TooltipField = value;
                    this.RaisePropertyChanged("Tooltip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIdField, value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AOS.DataAccessLayer.PhoneList75.PhoneListPreferences))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AOS.DataAccessLayer.PhoneList75.PhoneListItem))]
    public partial class Carrier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.TableRight TableRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.FieldPropertyDictionary FieldPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.PhoneList75.TableRight TableRight {
            get {
                return this.TableRightField;
            }
            set {
                if ((object.ReferenceEquals(this.TableRightField, value) != true)) {
                    this.TableRightField = value;
                    this.RaisePropertyChanged("TableRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public AOS.DataAccessLayer.PhoneList75.FieldPropertyDictionary FieldProperties {
            get {
                return this.FieldPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldPropertiesField, value) != true)) {
                    this.FieldPropertiesField = value;
                    this.RaisePropertyChanged("FieldProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class TableRight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.ETableRight MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.PhoneList75.ETableRight Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((this.MaskField.Equals(value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneListPreferences", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class PhoneListPreferences : AOS.DataAccessLayer.PhoneList75.Carrier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchFirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchLastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeFirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeLastnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchCompany {
            get {
                return this.SearchCompanyField;
            }
            set {
                if ((this.SearchCompanyField.Equals(value) != true)) {
                    this.SearchCompanyField = value;
                    this.RaisePropertyChanged("SearchCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchFirstname {
            get {
                return this.SearchFirstnameField;
            }
            set {
                if ((this.SearchFirstnameField.Equals(value) != true)) {
                    this.SearchFirstnameField = value;
                    this.RaisePropertyChanged("SearchFirstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchLastname {
            get {
                return this.SearchLastnameField;
            }
            set {
                if ((this.SearchLastnameField.Equals(value) != true)) {
                    this.SearchLastnameField = value;
                    this.RaisePropertyChanged("SearchLastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool SearchDepartment {
            get {
                return this.SearchDepartmentField;
            }
            set {
                if ((this.SearchDepartmentField.Equals(value) != true)) {
                    this.SearchDepartmentField = value;
                    this.RaisePropertyChanged("SearchDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeCompany {
            get {
                return this.SearchModeCompanyField;
            }
            set {
                if ((this.SearchModeCompanyField.Equals(value) != true)) {
                    this.SearchModeCompanyField = value;
                    this.RaisePropertyChanged("SearchModeCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeDepartment {
            get {
                return this.SearchModeDepartmentField;
            }
            set {
                if ((this.SearchModeDepartmentField.Equals(value) != true)) {
                    this.SearchModeDepartmentField = value;
                    this.RaisePropertyChanged("SearchModeDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeFirstname {
            get {
                return this.SearchModeFirstnameField;
            }
            set {
                if ((this.SearchModeFirstnameField.Equals(value) != true)) {
                    this.SearchModeFirstnameField = value;
                    this.RaisePropertyChanged("SearchModeFirstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public AOS.DataAccessLayer.PhoneList75.StringSearchType SearchModeLastname {
            get {
                return this.SearchModeLastnameField;
            }
            set {
                if ((this.SearchModeLastnameField.Equals(value) != true)) {
                    this.SearchModeLastnameField = value;
                    this.RaisePropertyChanged("SearchModeLastname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FieldPropertyDictionary", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", ItemName="FieldPropertyDictionaryKeyValuePair", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class FieldPropertyDictionary : System.Collections.Generic.Dictionary<string, AOS.DataAccessLayer.PhoneList75.FieldProperty> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    public enum ETableRight : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Select = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Filtering = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedUpdate = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uninitialized = 128,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldProperty", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class FieldProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.FieldRight FieldRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldLengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.PhoneList75.FieldRight FieldRight {
            get {
                return this.FieldRightField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldRightField, value) != true)) {
                    this.FieldRightField = value;
                    this.RaisePropertyChanged("FieldRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType {
            get {
                return this.FieldTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldTypeField, value) != true)) {
                    this.FieldTypeField = value;
                    this.RaisePropertyChanged("FieldType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int FieldLength {
            get {
                return this.FieldLengthField;
            }
            set {
                if ((this.FieldLengthField.Equals(value) != true)) {
                    this.FieldLengthField = value;
                    this.RaisePropertyChanged("FieldLength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringSearchType", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    public enum StringSearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exact = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeginsWith = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndsWith = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    [System.SerializableAttribute()]
    public partial class FieldRight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.PhoneList75.EFieldRight MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.PhoneList75.EFieldRight Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((this.MaskField.Equals(value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EFieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
    public enum EFieldRight : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Write = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused3 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused4 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintMandatory = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintReadOnly = 128,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", ConfigurationName="PhoneList75.PhoneList")]
    public interface PhoneList {
        
        // CODEGEN: Generating message contract since message SearchRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/Search", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SearchResponse")]
        AOS.DataAccessLayer.PhoneList75.SearchResponse Search(AOS.DataAccessLayer.PhoneList75.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/Search", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SearchResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SearchResponse> SearchAsync(AOS.DataAccessLayer.PhoneList75.SearchRequest request);
        
        // CODEGEN: Generating message contract since message SearchWithPreferencesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SearchWithPrefer" +
            "ences", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SearchWithPrefer" +
            "encesResponse")]
        AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesResponse SearchWithPreferences(AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SearchWithPrefer" +
            "ences", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SearchWithPrefer" +
            "encesResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesResponse> SearchWithPreferencesAsync(AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest request);
        
        // CODEGEN: Generating message contract since message GetDepartmentPhonesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetDepartmentPho" +
            "nes", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetDepartmentPho" +
            "nesResponse")]
        AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesResponse GetDepartmentPhones(AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetDepartmentPho" +
            "nes", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetDepartmentPho" +
            "nesResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesResponse> GetDepartmentPhonesAsync(AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest request);
        
        // CODEGEN: Generating message contract since message GetFavoritesPhonesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetFavoritesPhon" +
            "es", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetFavoritesPhon" +
            "esResponse")]
        AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesResponse GetFavoritesPhones(AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetFavoritesPhon" +
            "es", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetFavoritesPhon" +
            "esResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesResponse> GetFavoritesPhonesAsync(AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest request);
        
        // CODEGEN: Generating message contract since message GetContactPhonesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetContactPhones" +
            "", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetContactPhones" +
            "Response")]
        AOS.DataAccessLayer.PhoneList75.GetContactPhonesResponse GetContactPhones(AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetContactPhones" +
            "", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetContactPhones" +
            "Response")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetContactPhonesResponse> GetContactPhonesAsync(AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest request);
        
        // CODEGEN: Generating message contract since message AddToFavoritesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/AddToFavorites", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/AddToFavoritesRe" +
            "sponse")]
        AOS.DataAccessLayer.PhoneList75.AddToFavoritesResponse AddToFavorites(AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/AddToFavorites", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/AddToFavoritesRe" +
            "sponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.AddToFavoritesResponse> AddToFavoritesAsync(AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest request);
        
        // CODEGEN: Generating message contract since message GetPreferencesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetPreferences", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetPreferencesRe" +
            "sponse")]
        AOS.DataAccessLayer.PhoneList75.GetPreferencesResponse GetPreferences(AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetPreferences", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/GetPreferencesRe" +
            "sponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetPreferencesResponse> GetPreferencesAsync(AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest request);
        
        // CODEGEN: Generating message contract since message SetPreferencesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SetPreferences", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SetPreferencesRe" +
            "sponse")]
        AOS.DataAccessLayer.PhoneList75.SetPreferencesResponse SetPreferences(AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SetPreferences", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services75/PhoneList/SetPreferencesRe" +
            "sponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SetPreferencesResponse> SetPreferencesAsync(AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public string SearchString;
        
        public SearchRequest() {
        }
        
        public SearchRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, string SearchString) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.SearchString = SearchString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response;
        
        public SearchResponse() {
        }
        
        public SearchResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchWithPreferences", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class SearchWithPreferencesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public string SearchString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=1)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences;
        
        public SearchWithPreferencesRequest() {
        }
        
        public SearchWithPreferencesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, string SearchString, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.SearchString = SearchString;
            this.Preferences = Preferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchWithPreferencesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class SearchWithPreferencesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response;
        
        public SearchWithPreferencesResponse() {
        }
        
        public SearchWithPreferencesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartmentPhones", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetDepartmentPhonesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public int DepartmentId;
        
        public GetDepartmentPhonesRequest() {
        }
        
        public GetDepartmentPhonesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int DepartmentId) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.DepartmentId = DepartmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartmentPhonesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetDepartmentPhonesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response;
        
        public GetDepartmentPhonesResponse() {
        }
        
        public GetDepartmentPhonesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFavoritesPhones", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetFavoritesPhonesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        public GetFavoritesPhonesRequest() {
        }
        
        public GetFavoritesPhonesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFavoritesPhonesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetFavoritesPhonesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response;
        
        public GetFavoritesPhonesResponse() {
        }
        
        public GetFavoritesPhonesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactPhones", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetContactPhonesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public int ContactId;
        
        public GetContactPhonesRequest() {
        }
        
        public GetContactPhonesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int ContactId) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.ContactId = ContactId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactPhonesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetContactPhonesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response;
        
        public GetContactPhonesResponse() {
        }
        
        public GetContactPhonesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToFavorites", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class AddToFavoritesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public int ContactId;
        
        public AddToFavoritesRequest() {
        }
        
        public AddToFavoritesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int ContactId) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.ContactId = ContactId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToFavoritesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class AddToFavoritesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public int Response;
        
        public AddToFavoritesResponse() {
        }
        
        public AddToFavoritesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPreferences", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetPreferencesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        public GetPreferencesRequest() {
        }
        
        public GetPreferencesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPreferencesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class GetPreferencesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Response;
        
        public GetPreferencesResponse() {
        }
        
        public GetPreferencesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPreferences", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class SetPreferencesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75", Order=0)]
        public AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences;
        
        public SetPreferencesRequest() {
        }
        
        public SetPreferencesRequest(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.Preferences = Preferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPreferencesResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services75", IsWrapped=true)]
    public partial class SetPreferencesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services75")]
        public AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone;
        
        public SetPreferencesResponse() {
        }
        
        public SetPreferencesResponse(AOS.DataAccessLayer.PhoneList75.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhoneListChannel : AOS.DataAccessLayer.PhoneList75.PhoneList, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneListClient : System.ServiceModel.ClientBase<AOS.DataAccessLayer.PhoneList75.PhoneList>, AOS.DataAccessLayer.PhoneList75.PhoneList {
        
        public PhoneListClient() {
        }
        
        public PhoneListClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneListClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneListClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneListClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.SearchResponse AOS.DataAccessLayer.PhoneList75.PhoneList.Search(AOS.DataAccessLayer.PhoneList75.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo Search(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, string SearchString, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            AOS.DataAccessLayer.PhoneList75.SearchRequest inValue = new AOS.DataAccessLayer.PhoneList75.SearchRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.SearchString = SearchString;
            AOS.DataAccessLayer.PhoneList75.SearchResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).Search(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SearchResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.SearchAsync(AOS.DataAccessLayer.PhoneList75.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SearchResponse> SearchAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, string SearchString) {
            AOS.DataAccessLayer.PhoneList75.SearchRequest inValue = new AOS.DataAccessLayer.PhoneList75.SearchRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.SearchString = SearchString;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.SearchWithPreferences(AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest request) {
            return base.Channel.SearchWithPreferences(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo SearchWithPreferences(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, string SearchString, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest inValue = new AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.SearchString = SearchString;
            inValue.Preferences = Preferences;
            AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).SearchWithPreferences(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.SearchWithPreferencesAsync(AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest request) {
            return base.Channel.SearchWithPreferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesResponse> SearchWithPreferencesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, string SearchString, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences) {
            AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest inValue = new AOS.DataAccessLayer.PhoneList75.SearchWithPreferencesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.SearchString = SearchString;
            inValue.Preferences = Preferences;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).SearchWithPreferencesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.GetDepartmentPhones(AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest request) {
            return base.Channel.GetDepartmentPhones(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo GetDepartmentPhones(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int DepartmentId, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.DepartmentId = DepartmentId;
            AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetDepartmentPhones(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.GetDepartmentPhonesAsync(AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest request) {
            return base.Channel.GetDepartmentPhonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesResponse> GetDepartmentPhonesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int DepartmentId) {
            AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetDepartmentPhonesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.DepartmentId = DepartmentId;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetDepartmentPhonesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.GetFavoritesPhones(AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest request) {
            return base.Channel.GetFavoritesPhones(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo GetFavoritesPhones(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetFavoritesPhones(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.GetFavoritesPhonesAsync(AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest request) {
            return base.Channel.GetFavoritesPhonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesResponse> GetFavoritesPhonesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone) {
            AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetFavoritesPhonesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetFavoritesPhonesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.GetContactPhonesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.GetContactPhones(AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest request) {
            return base.Channel.GetContactPhones(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo GetContactPhones(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int ContactId, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.PhoneList75.PhoneListItem[] Response) {
            AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.ContactId = ContactId;
            AOS.DataAccessLayer.PhoneList75.GetContactPhonesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetContactPhones(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetContactPhonesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.GetContactPhonesAsync(AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest request) {
            return base.Channel.GetContactPhonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetContactPhonesResponse> GetContactPhonesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int ContactId) {
            AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetContactPhonesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.ContactId = ContactId;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetContactPhonesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.AddToFavoritesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.AddToFavorites(AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest request) {
            return base.Channel.AddToFavorites(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo AddToFavorites(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int ContactId, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out int Response) {
            AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest inValue = new AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.ContactId = ContactId;
            AOS.DataAccessLayer.PhoneList75.AddToFavoritesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).AddToFavorites(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.AddToFavoritesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.AddToFavoritesAsync(AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest request) {
            return base.Channel.AddToFavoritesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.AddToFavoritesResponse> AddToFavoritesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, int ContactId) {
            AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest inValue = new AOS.DataAccessLayer.PhoneList75.AddToFavoritesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.ContactId = ContactId;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).AddToFavoritesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.GetPreferencesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.GetPreferences(AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest request) {
            return base.Channel.GetPreferences(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo GetPreferences(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Response) {
            AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            AOS.DataAccessLayer.PhoneList75.GetPreferencesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetPreferences(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetPreferencesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.GetPreferencesAsync(AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest request) {
            return base.Channel.GetPreferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.GetPreferencesResponse> GetPreferencesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone) {
            AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest inValue = new AOS.DataAccessLayer.PhoneList75.GetPreferencesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).GetPreferencesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.PhoneList75.SetPreferencesResponse AOS.DataAccessLayer.PhoneList75.PhoneList.SetPreferences(AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest request) {
            return base.Channel.SetPreferences(request);
        }
        
        public AOS.DataAccessLayer.PhoneList75.SoExceptionInfo SetPreferences(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, ref AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences, out AOS.DataAccessLayer.PhoneList75.SoExtraInfo ExtraInfo, out bool Succeeded) {
            AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest inValue = new AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.Preferences = Preferences;
            AOS.DataAccessLayer.PhoneList75.SetPreferencesResponse retVal = ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).SetPreferences(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SetPreferencesResponse> AOS.DataAccessLayer.PhoneList75.PhoneList.SetPreferencesAsync(AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest request) {
            return base.Channel.SetPreferencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.PhoneList75.SetPreferencesResponse> SetPreferencesAsync(string ApplicationToken, AOS.DataAccessLayer.PhoneList75.SoCredentials Credentials, AOS.DataAccessLayer.PhoneList75.SoTimeZone TimeZone, AOS.DataAccessLayer.PhoneList75.PhoneListPreferences Preferences) {
            AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest inValue = new AOS.DataAccessLayer.PhoneList75.SetPreferencesRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.Preferences = Preferences;
            return ((AOS.DataAccessLayer.PhoneList75.PhoneList)(this)).SetPreferencesAsync(inValue);
        }
    }
}
