//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DataAccessLayer
{
    using AOS.DomainModel;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AOSEntities : DbContext
    {
        public AOSEntities()
            : base("name=AOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountApp> AccountApp { get; set; }
        public virtual DbSet<AccountAppAssociate> AccountAppAssociate { get; set; }
        public virtual DbSet<Addressbook> Addressbook { get; set; }
        public virtual DbSet<APIKey> APIKey { get; set; }
        public virtual DbSet<App> App { get; set; }
        public virtual DbSet<AppIcons> AppIcons { get; set; }
        public virtual DbSet<AppPrivateKey> AppPrivateKey { get; set; }
        public virtual DbSet<AppState> AppState { get; set; }
        public virtual DbSet<AppSystemUserToken> AppSystemUserToken { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BisNodeInfo> BisNodeInfo { get; set; }
        public virtual DbSet<BisnodeManager> BisnodeManager { get; set; }
        public virtual DbSet<Connection> Connection { get; set; }
        public virtual DbSet<Converter> Converter { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Dashboard> Dashboard { get; set; }
        public virtual DbSet<DataSync> DataSync { get; set; }
        public virtual DbSet<ElasticIO> ElasticIO { get; set; }
        public virtual DbSet<Globals> Globals { get; set; }
        public virtual DbSet<InstallInfo> InstallInfo { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogGroup> LogGroup { get; set; }
        public virtual DbSet<MachineName> MachineName { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }
        public virtual DbSet<MatchPerson> MatchPerson { get; set; }
        public virtual DbSet<MirroringLog> MirroringLog { get; set; }
        public virtual DbSet<MirroringLogLevel> MirroringLogLevel { get; set; }
        public virtual DbSet<MirroringLogType> MirroringLogType { get; set; }
        public virtual DbSet<MirroringStatus> MirroringStatus { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<PBXDial> PBXDial { get; set; }
        public virtual DbSet<PDFManager> PDFManager { get; set; }
        public virtual DbSet<Referral> Referral { get; set; }
        public virtual DbSet<RelationWise> RelationWise { get; set; }
        public virtual DbSet<RWAppointmentStatus> RWAppointmentStatus { get; set; }
        public virtual DbSet<RWAppointmentTask> RWAppointmentTask { get; set; }
        public virtual DbSet<RWAppointmentTrigger> RWAppointmentTrigger { get; set; }
        public virtual DbSet<RWChosenVariable> RWChosenVariable { get; set; }
        public virtual DbSet<RWSaleStatus> RWSaleStatus { get; set; }
        public virtual DbSet<RWSaleTrigger> RWSaleTrigger { get; set; }
        public virtual DbSet<RWSOVariable> RWSOVariable { get; set; }
        public virtual DbSet<RWTrigger> RWTrigger { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<Signicat> Signicat { get; set; }
        public virtual DbSet<SignicatAccountSignLanguage> SignicatAccountSignLanguage { get; set; }
        public virtual DbSet<SignicatAccountSignMethod> SignicatAccountSignMethod { get; set; }
        public virtual DbSet<SignicatDocumentTemplate> SignicatDocumentTemplate { get; set; }
        public virtual DbSet<SignicatEmail> SignicatEmail { get; set; }
        public virtual DbSet<SignicatEventStatus> SignicatEventStatus { get; set; }
        public virtual DbSet<SignicatLanguage> SignicatLanguage { get; set; }
        public virtual DbSet<SignicatLogging> SignicatLogging { get; set; }
        public virtual DbSet<SignicatSecureForm> SignicatSecureForm { get; set; }
        public virtual DbSet<SignicatSignMethod> SignicatSignMethod { get; set; }
        public virtual DbSet<SignicatStatus> SignicatStatus { get; set; }
        public virtual DbSet<SOCertificate> SOCertificate { get; set; }
        public virtual DbSet<SOInclude> SOInclude { get; set; }
        public virtual DbSet<SyncContact> SyncContact { get; set; }
        public virtual DbSet<SyncPerson> SyncPerson { get; set; }
        public virtual DbSet<SyncSale> SyncSale { get; set; }
        public virtual DbSet<Text> Text { get; set; }
        public virtual DbSet<TextType> TextType { get; set; }
        public virtual DbSet<UserRoleAccount> UserRoleAccount { get; set; }
        public virtual DbSet<VisibleIn> VisibleIn { get; set; }
        public virtual DbSet<Zapier> Zapier { get; set; }
        public virtual DbSet<DocArcActivity> DocArcActivity { get; set; }
        public virtual DbSet<SignicatEventLog> SignicatEventLog { get; set; }
        public virtual DbSet<SignicatEventOrigin> SignicatEventOrigin { get; set; }
        public virtual DbSet<SignicatEventType> SignicatEventType { get; set; }
        public virtual DbSet<AppOnlineProvisioning> AppOnlineProvisioning { get; set; }
        public virtual DbSet<DocArcAssociation> DocArcAssociation { get; set; }
        public virtual DbSet<DocArcLog4net> DocArcLog4net { get; set; }
        public virtual DbSet<DocArcTemplate> DocArcTemplate { get; set; }
        public virtual DbSet<DocArcAdministrators> DocArcAdministrators { get; set; }
        public virtual DbSet<LOISLicenseCompany> LOISLicenseCompany { get; set; }
        public virtual DbSet<LOISLicenseCompanyKeys> LOISLicenseCompanyKeys { get; set; }
    }
}
