//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOS.DataAccessLayer.Associate82 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class SoCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoTimeZone", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class SoTimeZone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoTimeZoneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoTimeZoneLocationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTimeZoneId {
            get {
                return this.SoTimeZoneIdField;
            }
            set {
                if ((this.SoTimeZoneIdField.Equals(value) != true)) {
                    this.SoTimeZoneIdField = value;
                    this.RaisePropertyChanged("SoTimeZoneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTimeZoneLocationCode {
            get {
                return this.SoTimeZoneLocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SoTimeZoneLocationCodeField, value) != true)) {
                    this.SoTimeZoneLocationCodeField = value;
                    this.RaisePropertyChanged("SoTimeZoneLocationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoExceptionInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class SoExceptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FriendlyTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.SoExceptionInfo InnerExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.SoExceptionInfoParameters ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FriendlyText {
            get {
                return this.FriendlyTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendlyTextField, value) != true)) {
                    this.FriendlyTextField = value;
                    this.RaisePropertyChanged("FriendlyText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfoParameters Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExceptionInfoParameters", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", ItemName="SoExceptionInfoParametersKeyValuePair", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class SoExceptionInfoParameters : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExtraInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", ItemName="ExtraInfoNameValuePair", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class SoExtraInfo : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AOS.DataAccessLayer.Associate82.Associate))]
    public partial class Carrier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.TableRight TableRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.FieldPropertyDictionary FieldPropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.Associate82.TableRight TableRight {
            get {
                return this.TableRightField;
            }
            set {
                if ((object.ReferenceEquals(this.TableRightField, value) != true)) {
                    this.TableRightField = value;
                    this.RaisePropertyChanged("TableRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public AOS.DataAccessLayer.Associate82.FieldPropertyDictionary FieldProperties {
            get {
                return this.FieldPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldPropertiesField, value) != true)) {
                    this.FieldPropertiesField = value;
                    this.RaisePropertyChanged("FieldProperties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class TableRight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.ETableRight MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.Associate82.ETableRight Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((this.MaskField.Equals(value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associate", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class Associate : AOS.DataAccessLayer.Associate82.Carrier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssociateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TooltipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.UserType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EjUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssociateId {
            get {
                return this.AssociateIdField;
            }
            set {
                if ((this.AssociateIdField.Equals(value) != true)) {
                    this.AssociateIdField = value;
                    this.RaisePropertyChanged("AssociateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tooltip {
            get {
                return this.TooltipField;
            }
            set {
                if ((object.ReferenceEquals(this.TooltipField, value) != true)) {
                    this.TooltipField = value;
                    this.RaisePropertyChanged("Tooltip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.Associate82.UserType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int GroupIdx {
            get {
                return this.GroupIdxField;
            }
            set {
                if ((this.GroupIdxField.Equals(value) != true)) {
                    this.GroupIdxField = value;
                    this.RaisePropertyChanged("GroupIdx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string FormalName {
            get {
                return this.FormalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormalNameField, value) != true)) {
                    this.FormalNameField = value;
                    this.RaisePropertyChanged("FormalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int EjUserId {
            get {
                return this.EjUserIdField;
            }
            set {
                if ((this.EjUserIdField.Equals(value) != true)) {
                    this.EjUserIdField = value;
                    this.RaisePropertyChanged("EjUserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FieldPropertyDictionary", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", ItemName="FieldPropertyDictionaryKeyValuePair", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class FieldPropertyDictionary : System.Collections.Generic.Dictionary<string, AOS.DataAccessLayer.Associate82.FieldProperty> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalAssociate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceAssociate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalAssociate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnonymousAssociate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAssociate = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    public enum ETableRight : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Select = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Filtering = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedUpdate = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldProperty", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class FieldProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.FieldRight FieldRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldLengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.Associate82.FieldRight FieldRight {
            get {
                return this.FieldRightField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldRightField, value) != true)) {
                    this.FieldRightField = value;
                    this.RaisePropertyChanged("FieldRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType {
            get {
                return this.FieldTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldTypeField, value) != true)) {
                    this.FieldTypeField = value;
                    this.RaisePropertyChanged("FieldType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int FieldLength {
            get {
                return this.FieldLengthField;
            }
            set {
                if ((this.FieldLengthField.Equals(value) != true)) {
                    this.FieldLengthField = value;
                    this.RaisePropertyChanged("FieldLength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    [System.SerializableAttribute()]
    public partial class FieldRight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AOS.DataAccessLayer.Associate82.EFieldRight MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AOS.DataAccessLayer.Associate82.EFieldRight Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((this.MaskField.Equals(value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EFieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
    public enum EFieldRight : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Write = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused3 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused4 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintMandatory = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintReadOnly = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UndefinedValue256 = 256,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Associate", Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", ConfigurationName="Associate82.Associate1")]
    public interface Associate1 {
        
        // CODEGEN: Generating message contract since message GetAssociateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociate", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateResp" +
            "onse")]
        AOS.DataAccessLayer.Associate82.GetAssociateResponse GetAssociate(AOS.DataAccessLayer.Associate82.GetAssociateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociate", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateResp" +
            "onse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateResponse> GetAssociateAsync(AOS.DataAccessLayer.Associate82.GetAssociateRequest request);
        
        // CODEGEN: Generating message contract since message GetAssociateByPersonIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateByPe" +
            "rsonId", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateByPe" +
            "rsonIdResponse")]
        AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdResponse GetAssociateByPersonId(AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateByPe" +
            "rsonId", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateByPe" +
            "rsonIdResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdResponse> GetAssociateByPersonIdAsync(AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest request);
        
        // CODEGEN: Generating message contract since message GetNoteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetNote", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetNoteResponse")]
        AOS.DataAccessLayer.Associate82.GetNoteResponse GetNote(AOS.DataAccessLayer.Associate82.GetNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetNote", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetNoteResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetNoteResponse> GetNoteAsync(AOS.DataAccessLayer.Associate82.GetNoteRequest request);
        
        // CODEGEN: Generating message contract since message SaveNoteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/SaveNote", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/SaveNoteResponse" +
            "")]
        AOS.DataAccessLayer.Associate82.SaveNoteResponse SaveNote(AOS.DataAccessLayer.Associate82.SaveNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/SaveNote", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/SaveNoteResponse" +
            "")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.SaveNoteResponse> SaveNoteAsync(AOS.DataAccessLayer.Associate82.SaveNoteRequest request);
        
        // CODEGEN: Generating message contract since message GetAssociateListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateList" +
            "", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateList" +
            "Response")]
        AOS.DataAccessLayer.Associate82.GetAssociateListResponse GetAssociateList(AOS.DataAccessLayer.Associate82.GetAssociateListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateList" +
            "", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociateList" +
            "Response")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateListResponse> GetAssociateListAsync(AOS.DataAccessLayer.Associate82.GetAssociateListRequest request);
        
        // CODEGEN: Generating message contract since message GetAssociatesByGroupRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociatesByG" +
            "roup", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociatesByG" +
            "roupResponse")]
        AOS.DataAccessLayer.Associate82.GetAssociatesByGroupResponse GetAssociatesByGroup(AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociatesByG" +
            "roup", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/GetAssociatesByG" +
            "roupResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociatesByGroupResponse> GetAssociatesByGroupAsync(AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest request);
        
        // CODEGEN: Generating message contract since message LogOffWindowsUsersRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/LogOffWindowsUse" +
            "rs", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/LogOffWindowsUse" +
            "rsResponse")]
        AOS.DataAccessLayer.Associate82.LogOffWindowsUsersResponse LogOffWindowsUsers(AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/LogOffWindowsUse" +
            "rs", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/Services82/Associate/LogOffWindowsUse" +
            "rsResponse")]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.LogOffWindowsUsersResponse> LogOffWindowsUsersAsync(AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociate", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int AssociateId;
        
        public GetAssociateRequest() {
        }
        
        public GetAssociateRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateId = AssociateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public AOS.DataAccessLayer.Associate82.Associate Response;
        
        public GetAssociateResponse() {
        }
        
        public GetAssociateResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, AOS.DataAccessLayer.Associate82.Associate Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateByPersonId", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociateByPersonIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int PersonId;
        
        public GetAssociateByPersonIdRequest() {
        }
        
        public GetAssociateByPersonIdRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int PersonId) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.PersonId = PersonId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateByPersonIdResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociateByPersonIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public AOS.DataAccessLayer.Associate82.Associate Response;
        
        public GetAssociateByPersonIdResponse() {
        }
        
        public GetAssociateByPersonIdResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, AOS.DataAccessLayer.Associate82.Associate Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNote", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetNoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int AssociateId;
        
        public GetNoteRequest() {
        }
        
        public GetNoteRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateId = AssociateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNoteResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetNoteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public string[] Response;
        
        public GetNoteResponse() {
        }
        
        public GetNoteResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, string[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveNote", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class SaveNoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int AssociateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=1)]
        public string[] Note;
        
        public SaveNoteRequest() {
        }
        
        public SaveNoteRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId, string[] Note) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateId = AssociateId;
            this.Note = Note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveNoteResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class SaveNoteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        public SaveNoteResponse() {
        }
        
        public SaveNoteResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateList", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociateListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int[] AssociateIds;
        
        public GetAssociateListRequest() {
        }
        
        public GetAssociateListRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int[] AssociateIds) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateIds = AssociateIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateListResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociateListResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public AOS.DataAccessLayer.Associate82.Associate[] Response;
        
        public GetAssociateListResponse() {
        }
        
        public GetAssociateListResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, AOS.DataAccessLayer.Associate82.Associate[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociatesByGroup", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociatesByGroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int GroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=1)]
        public int Type;
        
        public GetAssociatesByGroupRequest() {
        }
        
        public GetAssociatesByGroupRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int GroupId, int Type) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.GroupId = GroupId;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociatesByGroupResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class GetAssociatesByGroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public AOS.DataAccessLayer.Associate82.Associate[] Response;
        
        public GetAssociatesByGroupResponse() {
        }
        
        public GetAssociatesByGroupResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, AOS.DataAccessLayer.Associate82.Associate[] Response) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogOffWindowsUsers", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class LogOffWindowsUsersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82", Order=0)]
        public int[] AssociateIds;
        
        public LogOffWindowsUsersRequest() {
        }
        
        public LogOffWindowsUsersRequest(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int[] AssociateIds) {
            this.ApplicationToken = ApplicationToken;
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateIds = AssociateIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogOffWindowsUsersResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/Services82", IsWrapped=true)]
    public partial class LogOffWindowsUsersResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/Services82")]
        public AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone;
        
        public LogOffWindowsUsersResponse() {
        }
        
        public LogOffWindowsUsersResponse(AOS.DataAccessLayer.Associate82.SoExceptionInfo ExceptionInfo, AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, bool Succeeded, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone) {
            this.ExceptionInfo = ExceptionInfo;
            this.ExtraInfo = ExtraInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Associate1Channel : AOS.DataAccessLayer.Associate82.Associate1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Associate1Client : System.ServiceModel.ClientBase<AOS.DataAccessLayer.Associate82.Associate1>, AOS.DataAccessLayer.Associate82.Associate1 {
        
        public Associate1Client() {
        }
        
        public Associate1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Associate1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Associate1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Associate1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.GetAssociateResponse AOS.DataAccessLayer.Associate82.Associate1.GetAssociate(AOS.DataAccessLayer.Associate82.GetAssociateRequest request) {
            return base.Channel.GetAssociate(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo GetAssociate(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.Associate82.Associate Response) {
            AOS.DataAccessLayer.Associate82.GetAssociateRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociateRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            AOS.DataAccessLayer.Associate82.GetAssociateResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociate(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateResponse> AOS.DataAccessLayer.Associate82.Associate1.GetAssociateAsync(AOS.DataAccessLayer.Associate82.GetAssociateRequest request) {
            return base.Channel.GetAssociateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateResponse> GetAssociateAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId) {
            AOS.DataAccessLayer.Associate82.GetAssociateRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociateRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdResponse AOS.DataAccessLayer.Associate82.Associate1.GetAssociateByPersonId(AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest request) {
            return base.Channel.GetAssociateByPersonId(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo GetAssociateByPersonId(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int PersonId, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.Associate82.Associate Response) {
            AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.PersonId = PersonId;
            AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociateByPersonId(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdResponse> AOS.DataAccessLayer.Associate82.Associate1.GetAssociateByPersonIdAsync(AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest request) {
            return base.Channel.GetAssociateByPersonIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdResponse> GetAssociateByPersonIdAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int PersonId) {
            AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociateByPersonIdRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.PersonId = PersonId;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociateByPersonIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.GetNoteResponse AOS.DataAccessLayer.Associate82.Associate1.GetNote(AOS.DataAccessLayer.Associate82.GetNoteRequest request) {
            return base.Channel.GetNote(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo GetNote(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded, out string[] Response) {
            AOS.DataAccessLayer.Associate82.GetNoteRequest inValue = new AOS.DataAccessLayer.Associate82.GetNoteRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            AOS.DataAccessLayer.Associate82.GetNoteResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetNote(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetNoteResponse> AOS.DataAccessLayer.Associate82.Associate1.GetNoteAsync(AOS.DataAccessLayer.Associate82.GetNoteRequest request) {
            return base.Channel.GetNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetNoteResponse> GetNoteAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId) {
            AOS.DataAccessLayer.Associate82.GetNoteRequest inValue = new AOS.DataAccessLayer.Associate82.GetNoteRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.SaveNoteResponse AOS.DataAccessLayer.Associate82.Associate1.SaveNote(AOS.DataAccessLayer.Associate82.SaveNoteRequest request) {
            return base.Channel.SaveNote(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo SaveNote(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId, string[] Note, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded) {
            AOS.DataAccessLayer.Associate82.SaveNoteRequest inValue = new AOS.DataAccessLayer.Associate82.SaveNoteRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            inValue.Note = Note;
            AOS.DataAccessLayer.Associate82.SaveNoteResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).SaveNote(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.SaveNoteResponse> AOS.DataAccessLayer.Associate82.Associate1.SaveNoteAsync(AOS.DataAccessLayer.Associate82.SaveNoteRequest request) {
            return base.Channel.SaveNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.SaveNoteResponse> SaveNoteAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int AssociateId, string[] Note) {
            AOS.DataAccessLayer.Associate82.SaveNoteRequest inValue = new AOS.DataAccessLayer.Associate82.SaveNoteRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            inValue.Note = Note;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).SaveNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.GetAssociateListResponse AOS.DataAccessLayer.Associate82.Associate1.GetAssociateList(AOS.DataAccessLayer.Associate82.GetAssociateListRequest request) {
            return base.Channel.GetAssociateList(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo GetAssociateList(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int[] AssociateIds, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.Associate82.Associate[] Response) {
            AOS.DataAccessLayer.Associate82.GetAssociateListRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociateListRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateIds = AssociateIds;
            AOS.DataAccessLayer.Associate82.GetAssociateListResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociateList(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateListResponse> AOS.DataAccessLayer.Associate82.Associate1.GetAssociateListAsync(AOS.DataAccessLayer.Associate82.GetAssociateListRequest request) {
            return base.Channel.GetAssociateListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociateListResponse> GetAssociateListAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int[] AssociateIds) {
            AOS.DataAccessLayer.Associate82.GetAssociateListRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociateListRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateIds = AssociateIds;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociateListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.GetAssociatesByGroupResponse AOS.DataAccessLayer.Associate82.Associate1.GetAssociatesByGroup(AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest request) {
            return base.Channel.GetAssociatesByGroup(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo GetAssociatesByGroup(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int GroupId, int Type, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded, out AOS.DataAccessLayer.Associate82.Associate[] Response) {
            AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.GroupId = GroupId;
            inValue.Type = Type;
            AOS.DataAccessLayer.Associate82.GetAssociatesByGroupResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociatesByGroup(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociatesByGroupResponse> AOS.DataAccessLayer.Associate82.Associate1.GetAssociatesByGroupAsync(AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest request) {
            return base.Channel.GetAssociatesByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.GetAssociatesByGroupResponse> GetAssociatesByGroupAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int GroupId, int Type) {
            AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest inValue = new AOS.DataAccessLayer.Associate82.GetAssociatesByGroupRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.GroupId = GroupId;
            inValue.Type = Type;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).GetAssociatesByGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AOS.DataAccessLayer.Associate82.LogOffWindowsUsersResponse AOS.DataAccessLayer.Associate82.Associate1.LogOffWindowsUsers(AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest request) {
            return base.Channel.LogOffWindowsUsers(request);
        }
        
        public AOS.DataAccessLayer.Associate82.SoExceptionInfo LogOffWindowsUsers(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, ref AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int[] AssociateIds, out AOS.DataAccessLayer.Associate82.SoExtraInfo ExtraInfo, out bool Succeeded) {
            AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest inValue = new AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateIds = AssociateIds;
            AOS.DataAccessLayer.Associate82.LogOffWindowsUsersResponse retVal = ((AOS.DataAccessLayer.Associate82.Associate1)(this)).LogOffWindowsUsers(inValue);
            ExtraInfo = retVal.ExtraInfo;
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.LogOffWindowsUsersResponse> AOS.DataAccessLayer.Associate82.Associate1.LogOffWindowsUsersAsync(AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest request) {
            return base.Channel.LogOffWindowsUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<AOS.DataAccessLayer.Associate82.LogOffWindowsUsersResponse> LogOffWindowsUsersAsync(string ApplicationToken, AOS.DataAccessLayer.Associate82.SoCredentials Credentials, AOS.DataAccessLayer.Associate82.SoTimeZone TimeZone, int[] AssociateIds) {
            AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest inValue = new AOS.DataAccessLayer.Associate82.LogOffWindowsUsersRequest();
            inValue.ApplicationToken = ApplicationToken;
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateIds = AssociateIds;
            return ((AOS.DataAccessLayer.Associate82.Associate1)(this)).LogOffWindowsUsersAsync(inValue);
        }
    }
}
